// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inbound_product.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/lib/pq"
)

const bulkCreateProductReceiptItems = `-- name: BulkCreateProductReceiptItems :exec
INSERT INTO product_receipt_items (
  product_receipt_id, product_id, quantity
)
SELECT $1, unnest($2::bigint[]), unnest($3::numeric[])
RETURNING id, product_receipt_id, product_id, quantity, created_at, updated_at, deleted_at
`

type BulkCreateProductReceiptItemsParams struct {
	ProductReceiptID int64    `json:"product_receipt_id"`
	ProductIds       []int64  `json:"product_ids"`
	Quantities       []string `json:"quantities"`
}

func (q *Queries) BulkCreateProductReceiptItems(ctx context.Context, arg BulkCreateProductReceiptItemsParams) error {
	_, err := q.db.ExecContext(ctx, bulkCreateProductReceiptItems, arg.ProductReceiptID, pq.Array(arg.ProductIds), pq.Array(arg.Quantities))
	return err
}

const countIncomingSchedules = `-- name: CountIncomingSchedules :one
SELECT COUNT(*) FROM incoming_schedules
WHERE deleted_at IS NULL
`

func (q *Queries) CountIncomingSchedules(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countIncomingSchedules)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProductReceipts = `-- name: CountProductReceipts :one
SELECT COUNT(*) FROM product_receipts
WHERE deleted_at IS NULL
`

func (q *Queries) CountProductReceipts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProductReceipts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIncomingSchedule = `-- name: CreateIncomingSchedule :one
INSERT INTO incoming_schedules (
  location_id, po_number, expected_date, note
) VALUES ($1, $2, $3, $4)
RETURNING id, location_id, po_number, expected_date, status, note, received_quantity, created_at, updated_at, deleted_at
`

type CreateIncomingScheduleParams struct {
	LocationID   int64          `json:"location_id"`
	PoNumber     string         `json:"po_number"`
	ExpectedDate time.Time      `json:"expected_date"`
	Note         sql.NullString `json:"note"`
}

func (q *Queries) CreateIncomingSchedule(ctx context.Context, arg CreateIncomingScheduleParams) (IncomingSchedule, error) {
	row := q.db.QueryRowContext(ctx, createIncomingSchedule,
		arg.LocationID,
		arg.PoNumber,
		arg.ExpectedDate,
		arg.Note,
	)
	var i IncomingSchedule
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.PoNumber,
		&i.ExpectedDate,
		&i.Status,
		&i.Note,
		&i.ReceivedQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createProductReceipt = `-- name: CreateProductReceipt :one
INSERT INTO product_receipts (
  incoming_schedule_id, location_id, received_date, received_by, note
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, incoming_schedule_id, location_id, received_date, received_by, note, created_at, updated_at, deleted_at
`

type CreateProductReceiptParams struct {
	IncomingScheduleID sql.NullInt64  `json:"incoming_schedule_id"`
	LocationID         int64          `json:"location_id"`
	ReceivedDate       time.Time      `json:"received_date"`
	ReceivedBy         int64          `json:"received_by"`
	Note               sql.NullString `json:"note"`
}

func (q *Queries) CreateProductReceipt(ctx context.Context, arg CreateProductReceiptParams) (ProductReceipt, error) {
	row := q.db.QueryRowContext(ctx, createProductReceipt,
		arg.IncomingScheduleID,
		arg.LocationID,
		arg.ReceivedDate,
		arg.ReceivedBy,
		arg.Note,
	)
	var i ProductReceipt
	err := row.Scan(
		&i.ID,
		&i.IncomingScheduleID,
		&i.LocationID,
		&i.ReceivedDate,
		&i.ReceivedBy,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteIncomingSchedule = `-- name: DeleteIncomingSchedule :execresult
UPDATE incoming_schedules
SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteIncomingSchedule(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteIncomingSchedule, id)
}

const deleteIncomingScheduleItems = `-- name: DeleteIncomingScheduleItems :exec
UPDATE incoming_schedule_items
SET deleted_at = now()
WHERE incoming_schedule_id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteIncomingScheduleItems(ctx context.Context, incomingScheduleID int64) error {
	_, err := q.db.ExecContext(ctx, deleteIncomingScheduleItems, incomingScheduleID)
	return err
}

const getIncomingSchedule = `-- name: GetIncomingSchedule :one
SELECT id, location_id, po_number, expected_date, status, note, received_quantity, created_at, updated_at, deleted_at FROM incoming_schedules
WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetIncomingSchedule(ctx context.Context, id int64) (IncomingSchedule, error) {
	row := q.db.QueryRowContext(ctx, getIncomingSchedule, id)
	var i IncomingSchedule
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.PoNumber,
		&i.ExpectedDate,
		&i.Status,
		&i.Note,
		&i.ReceivedQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getIncomingScheduleItems = `-- name: GetIncomingScheduleItems :many
SELECT i.id, i.incoming_schedule_id, i.product_id, i.quantity, i.received_quantity, i.status, i.created_at, i.updated_at, i.deleted_at, p.name as product_name, p.sku_code as product_sku_code, p.uom as product_uom
FROM incoming_schedule_items i
JOIN products p ON i.product_id = p.id
WHERE i.incoming_schedule_id = $1 AND i.deleted_at IS NULL
`

type GetIncomingScheduleItemsRow struct {
	ID                 int64        `json:"id"`
	IncomingScheduleID int64        `json:"incoming_schedule_id"`
	ProductID          int64        `json:"product_id"`
	Quantity           string       `json:"quantity"`
	ReceivedQuantity   string       `json:"received_quantity"`
	Status             string       `json:"status"`
	CreatedAt          time.Time    `json:"created_at"`
	UpdatedAt          time.Time    `json:"updated_at"`
	DeletedAt          sql.NullTime `json:"deleted_at"`
	ProductName        string       `json:"product_name"`
	ProductSkuCode     string       `json:"product_sku_code"`
	ProductUom         string       `json:"product_uom"`
}

func (q *Queries) GetIncomingScheduleItems(ctx context.Context, incomingScheduleID int64) ([]GetIncomingScheduleItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, getIncomingScheduleItems, incomingScheduleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetIncomingScheduleItemsRow
	for rows.Next() {
		var i GetIncomingScheduleItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.IncomingScheduleID,
			&i.ProductID,
			&i.Quantity,
			&i.ReceivedQuantity,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ProductName,
			&i.ProductSkuCode,
			&i.ProductUom,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductReceipt = `-- name: GetProductReceipt :one
SELECT r.id, r.incoming_schedule_id, r.location_id, r.received_date, r.received_by, r.note, r.created_at, r.updated_at, r.deleted_at, 
       l.name as location_name, l.code as location_code,
       s.po_number as schedule_po_number, s.expected_date as schedule_expected_date
FROM product_receipts r
LEFT JOIN locations l ON r.location_id = l.id
LEFT JOIN incoming_schedules s ON r.incoming_schedule_id = s.id
WHERE r.id = $1 AND r.deleted_at IS NULL LIMIT 1
`

type GetProductReceiptRow struct {
	ID                   int64          `json:"id"`
	IncomingScheduleID   sql.NullInt64  `json:"incoming_schedule_id"`
	LocationID           int64          `json:"location_id"`
	ReceivedDate         time.Time      `json:"received_date"`
	ReceivedBy           int64          `json:"received_by"`
	Note                 sql.NullString `json:"note"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
	DeletedAt            sql.NullTime   `json:"deleted_at"`
	LocationName         sql.NullString `json:"location_name"`
	LocationCode         sql.NullString `json:"location_code"`
	SchedulePoNumber     sql.NullString `json:"schedule_po_number"`
	ScheduleExpectedDate sql.NullTime   `json:"schedule_expected_date"`
}

func (q *Queries) GetProductReceipt(ctx context.Context, id int64) (GetProductReceiptRow, error) {
	row := q.db.QueryRowContext(ctx, getProductReceipt, id)
	var i GetProductReceiptRow
	err := row.Scan(
		&i.ID,
		&i.IncomingScheduleID,
		&i.LocationID,
		&i.ReceivedDate,
		&i.ReceivedBy,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.LocationName,
		&i.LocationCode,
		&i.SchedulePoNumber,
		&i.ScheduleExpectedDate,
	)
	return i, err
}

const getProductReceiptItems = `-- name: GetProductReceiptItems :many
SELECT i.id, i.product_receipt_id, i.product_id, i.quantity, i.created_at, i.updated_at, i.deleted_at, p.name as product_name, p.sku_code as product_sku_code, p.uom as product_uom
FROM product_receipt_items i
JOIN products p ON i.product_id = p.id
WHERE i.product_receipt_id = $1 AND i.deleted_at IS NULL
`

type GetProductReceiptItemsRow struct {
	ID               int64        `json:"id"`
	ProductReceiptID int64        `json:"product_receipt_id"`
	ProductID        int64        `json:"product_id"`
	Quantity         string       `json:"quantity"`
	CreatedAt        time.Time    `json:"created_at"`
	UpdatedAt        time.Time    `json:"updated_at"`
	DeletedAt        sql.NullTime `json:"deleted_at"`
	ProductName      string       `json:"product_name"`
	ProductSkuCode   string       `json:"product_sku_code"`
	ProductUom       string       `json:"product_uom"`
}

func (q *Queries) GetProductReceiptItems(ctx context.Context, productReceiptID int64) ([]GetProductReceiptItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, getProductReceiptItems, productReceiptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductReceiptItemsRow
	for rows.Next() {
		var i GetProductReceiptItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductReceiptID,
			&i.ProductID,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ProductName,
			&i.ProductSkuCode,
			&i.ProductUom,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementScheduleItemReceivedQuantity = `-- name: IncrementScheduleItemReceivedQuantity :exec
UPDATE incoming_schedule_items
SET received_quantity = received_quantity + $3,
    updated_at = now()
WHERE incoming_schedule_id = $1 AND product_id = $2 AND deleted_at IS NULL
`

type IncrementScheduleItemReceivedQuantityParams struct {
	IncomingScheduleID int64  `json:"incoming_schedule_id"`
	ProductID          int64  `json:"product_id"`
	ReceivedQuantity   string `json:"received_quantity"`
}

func (q *Queries) IncrementScheduleItemReceivedQuantity(ctx context.Context, arg IncrementScheduleItemReceivedQuantityParams) error {
	_, err := q.db.ExecContext(ctx, incrementScheduleItemReceivedQuantity, arg.IncomingScheduleID, arg.ProductID, arg.ReceivedQuantity)
	return err
}

const incrementScheduleReceivedQuantity = `-- name: IncrementScheduleReceivedQuantity :exec
UPDATE incoming_schedules
SET received_quantity = received_quantity + $2,
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

type IncrementScheduleReceivedQuantityParams struct {
	ID               int64  `json:"id"`
	ReceivedQuantity string `json:"received_quantity"`
}

func (q *Queries) IncrementScheduleReceivedQuantity(ctx context.Context, arg IncrementScheduleReceivedQuantityParams) error {
	_, err := q.db.ExecContext(ctx, incrementScheduleReceivedQuantity, arg.ID, arg.ReceivedQuantity)
	return err
}

const listIncomingSchedules = `-- name: ListIncomingSchedules :many
SELECT id, location_id, po_number, expected_date, status, note, received_quantity, created_at, updated_at, deleted_at FROM incoming_schedules
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListIncomingSchedulesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListIncomingSchedules(ctx context.Context, arg ListIncomingSchedulesParams) ([]IncomingSchedule, error) {
	rows, err := q.db.QueryContext(ctx, listIncomingSchedules, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IncomingSchedule
	for rows.Next() {
		var i IncomingSchedule
		if err := rows.Scan(
			&i.ID,
			&i.LocationID,
			&i.PoNumber,
			&i.ExpectedDate,
			&i.Status,
			&i.Note,
			&i.ReceivedQuantity,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductReceipts = `-- name: ListProductReceipts :many
SELECT r.id, r.incoming_schedule_id, r.location_id, r.received_date, r.received_by, r.note, r.created_at, r.updated_at, r.deleted_at, 
       l.name as location_name, l.code as location_code,
       s.po_number as schedule_po_number, s.expected_date as schedule_expected_date
FROM product_receipts r
LEFT JOIN locations l ON r.location_id = l.id
LEFT JOIN incoming_schedules s ON r.incoming_schedule_id = s.id
WHERE r.deleted_at IS NULL
ORDER BY r.created_at DESC
LIMIT $1 OFFSET $2
`

type ListProductReceiptsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListProductReceiptsRow struct {
	ID                   int64          `json:"id"`
	IncomingScheduleID   sql.NullInt64  `json:"incoming_schedule_id"`
	LocationID           int64          `json:"location_id"`
	ReceivedDate         time.Time      `json:"received_date"`
	ReceivedBy           int64          `json:"received_by"`
	Note                 sql.NullString `json:"note"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
	DeletedAt            sql.NullTime   `json:"deleted_at"`
	LocationName         sql.NullString `json:"location_name"`
	LocationCode         sql.NullString `json:"location_code"`
	SchedulePoNumber     sql.NullString `json:"schedule_po_number"`
	ScheduleExpectedDate sql.NullTime   `json:"schedule_expected_date"`
}

func (q *Queries) ListProductReceipts(ctx context.Context, arg ListProductReceiptsParams) ([]ListProductReceiptsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProductReceipts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductReceiptsRow
	for rows.Next() {
		var i ListProductReceiptsRow
		if err := rows.Scan(
			&i.ID,
			&i.IncomingScheduleID,
			&i.LocationID,
			&i.ReceivedDate,
			&i.ReceivedBy,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.LocationName,
			&i.LocationCode,
			&i.SchedulePoNumber,
			&i.ScheduleExpectedDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIncomingSchedule = `-- name: UpdateIncomingSchedule :one
UPDATE incoming_schedules
SET location_id = $2, po_number = $3, expected_date = $4, status = $5, note = $6, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, location_id, po_number, expected_date, status, note, received_quantity, created_at, updated_at, deleted_at
`

type UpdateIncomingScheduleParams struct {
	ID           int64          `json:"id"`
	LocationID   int64          `json:"location_id"`
	PoNumber     string         `json:"po_number"`
	ExpectedDate time.Time      `json:"expected_date"`
	Status       string         `json:"status"`
	Note         sql.NullString `json:"note"`
}

func (q *Queries) UpdateIncomingSchedule(ctx context.Context, arg UpdateIncomingScheduleParams) (IncomingSchedule, error) {
	row := q.db.QueryRowContext(ctx, updateIncomingSchedule,
		arg.ID,
		arg.LocationID,
		arg.PoNumber,
		arg.ExpectedDate,
		arg.Status,
		arg.Note,
	)
	var i IncomingSchedule
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.PoNumber,
		&i.ExpectedDate,
		&i.Status,
		&i.Note,
		&i.ReceivedQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertIncomingScheduleItem = `-- name: UpsertIncomingScheduleItem :one
INSERT INTO incoming_schedule_items (
  incoming_schedule_id, product_id, quantity, received_quantity, status
) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (incoming_schedule_id, product_id) DO UPDATE SET
  quantity = EXCLUDED.quantity,
  received_quantity = EXCLUDED.received_quantity,
  status = EXCLUDED.status,
  updated_at = now(),
  deleted_at = NULL
RETURNING id, incoming_schedule_id, product_id, quantity, received_quantity, status, created_at, updated_at, deleted_at
`

type UpsertIncomingScheduleItemParams struct {
	IncomingScheduleID int64  `json:"incoming_schedule_id"`
	ProductID          int64  `json:"product_id"`
	Quantity           string `json:"quantity"`
	ReceivedQuantity   string `json:"received_quantity"`
	Status             string `json:"status"`
}

func (q *Queries) UpsertIncomingScheduleItem(ctx context.Context, arg UpsertIncomingScheduleItemParams) (IncomingScheduleItem, error) {
	row := q.db.QueryRowContext(ctx, upsertIncomingScheduleItem,
		arg.IncomingScheduleID,
		arg.ProductID,
		arg.Quantity,
		arg.ReceivedQuantity,
		arg.Status,
	)
	var i IncomingScheduleItem
	err := row.Scan(
		&i.ID,
		&i.IncomingScheduleID,
		&i.ProductID,
		&i.Quantity,
		&i.ReceivedQuantity,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
