// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inventory.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/lib/pq"
)

const bulkUpsertInventories = `-- name: BulkUpsertInventories :exec
INSERT INTO inventories (product_id, location_id, quantity, updated_at)
SELECT unnest($1::bigint[]), unnest($2::bigint[]), unnest($3::numeric[]), now()
ON CONFLICT (product_id, location_id) DO UPDATE SET
  quantity = EXCLUDED.quantity,
  updated_at = now()
`

type BulkUpsertInventoriesParams struct {
	ProductIds  []int64  `json:"product_ids"`
	LocationIds []int64  `json:"location_ids"`
	Quantities  []string `json:"quantities"`
}

func (q *Queries) BulkUpsertInventories(ctx context.Context, arg BulkUpsertInventoriesParams) error {
	_, err := q.db.ExecContext(ctx, bulkUpsertInventories, pq.Array(arg.ProductIds), pq.Array(arg.LocationIds), pq.Array(arg.Quantities))
	return err
}

const countInventories = `-- name: CountInventories :one
SELECT COUNT(*) FROM inventories i
JOIN products p ON i.product_id = p.id
JOIN locations l ON i.location_id = l.id
WHERE i.deleted_at IS NULL AND p.deleted_at IS NULL AND l.deleted_at IS NULL
`

func (q *Queries) CountInventories(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countInventories)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLocations = `-- name: CountLocations :one
SELECT COUNT(*) FROM locations
WHERE deleted_at IS NULL
  AND (name ILIKE $1 OR code ILIKE $1)
`

func (q *Queries) CountLocations(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLocations, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProducts = `-- name: CountProducts :one
SELECT COUNT(*) FROM products
WHERE deleted_at IS NULL
  AND (name ILIKE $1 OR sku_code ILIKE $1)
`

func (q *Queries) CountProducts(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProducts, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLocation = `-- name: CreateLocation :one
INSERT INTO locations (name, code)
VALUES ($1, $2)
RETURNING id, name, code, created_at, updated_at, deleted_at
`

type CreateLocationParams struct {
	Name string `json:"name"`
	Code string `json:"code"`
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error) {
	row := q.db.QueryRowContext(ctx, createLocation, arg.Name, arg.Code)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (name, sku_code, uom)
VALUES ($1, $2, $3)
RETURNING id, name, sku_code, uom, created_at, updated_at, deleted_at
`

type CreateProductParams struct {
	Name    string `json:"name"`
	SkuCode string `json:"sku_code"`
	Uom     string `json:"uom"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct, arg.Name, arg.SkuCode, arg.Uom)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SkuCode,
		&i.Uom,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteLocation = `-- name: DeleteLocation :execresult
UPDATE locations
SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteLocation(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteLocation, id)
}

const deleteProduct = `-- name: DeleteProduct :execresult
UPDATE products
SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteProduct(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteProduct, id)
}

const getInventoriesByLocation = `-- name: GetInventoriesByLocation :many
SELECT i.product_id, i.location_id, i.quantity, i.created_at, i.updated_at, i.deleted_at, p.name as product_name, p.sku_code as product_sku_code, p.uom as product_uom
FROM inventories i
JOIN products p ON i.product_id = p.id
WHERE i.location_id = $1 AND i.deleted_at IS NULL AND p.deleted_at IS NULL
`

type GetInventoriesByLocationRow struct {
	ProductID      int64        `json:"product_id"`
	LocationID     int64        `json:"location_id"`
	Quantity       string       `json:"quantity"`
	CreatedAt      time.Time    `json:"created_at"`
	UpdatedAt      time.Time    `json:"updated_at"`
	DeletedAt      sql.NullTime `json:"deleted_at"`
	ProductName    string       `json:"product_name"`
	ProductSkuCode string       `json:"product_sku_code"`
	ProductUom     string       `json:"product_uom"`
}

func (q *Queries) GetInventoriesByLocation(ctx context.Context, locationID int64) ([]GetInventoriesByLocationRow, error) {
	rows, err := q.db.QueryContext(ctx, getInventoriesByLocation, locationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetInventoriesByLocationRow
	for rows.Next() {
		var i GetInventoriesByLocationRow
		if err := rows.Scan(
			&i.ProductID,
			&i.LocationID,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ProductName,
			&i.ProductSkuCode,
			&i.ProductUom,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInventoriesByProduct = `-- name: GetInventoriesByProduct :many
SELECT i.product_id, i.location_id, i.quantity, i.created_at, i.updated_at, i.deleted_at, l.name as location_name, l.code as location_code
FROM inventories i
JOIN locations l ON i.location_id = l.id
WHERE i.product_id = $1 AND i.deleted_at IS NULL AND l.deleted_at IS NULL
`

type GetInventoriesByProductRow struct {
	ProductID    int64        `json:"product_id"`
	LocationID   int64        `json:"location_id"`
	Quantity     string       `json:"quantity"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
	DeletedAt    sql.NullTime `json:"deleted_at"`
	LocationName string       `json:"location_name"`
	LocationCode string       `json:"location_code"`
}

func (q *Queries) GetInventoriesByProduct(ctx context.Context, productID int64) ([]GetInventoriesByProductRow, error) {
	rows, err := q.db.QueryContext(ctx, getInventoriesByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetInventoriesByProductRow
	for rows.Next() {
		var i GetInventoriesByProductRow
		if err := rows.Scan(
			&i.ProductID,
			&i.LocationID,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.LocationName,
			&i.LocationCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInventoryStock = `-- name: GetInventoryStock :one
SELECT quantity FROM inventories
WHERE product_id = $1 AND location_id = $2 AND deleted_at IS NULL
`

type GetInventoryStockParams struct {
	ProductID  int64 `json:"product_id"`
	LocationID int64 `json:"location_id"`
}

func (q *Queries) GetInventoryStock(ctx context.Context, arg GetInventoryStockParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getInventoryStock, arg.ProductID, arg.LocationID)
	var quantity string
	err := row.Scan(&quantity)
	return quantity, err
}

const getLocation = `-- name: GetLocation :one
SELECT id, name, code, created_at, updated_at, deleted_at FROM locations
WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetLocation(ctx context.Context, id int64) (Location, error) {
	row := q.db.QueryRowContext(ctx, getLocation, id)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProduct = `-- name: GetProduct :one
SELECT id, name, sku_code, uom, created_at, updated_at, deleted_at FROM products
WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetProduct(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SkuCode,
		&i.Uom,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listInventories = `-- name: ListInventories :many
SELECT i.product_id, i.location_id, i.quantity, i.created_at, i.updated_at, i.deleted_at, 
       p.name as product_name, p.sku_code as product_sku_code, p.uom as product_uom,
       l.name as location_name, l.code as location_code
FROM inventories i
JOIN products p ON i.product_id = p.id
JOIN locations l ON i.location_id = l.id
WHERE i.deleted_at IS NULL AND p.deleted_at IS NULL AND l.deleted_at IS NULL
ORDER BY i.updated_at DESC
LIMIT $1 OFFSET $2
`

type ListInventoriesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListInventoriesRow struct {
	ProductID      int64        `json:"product_id"`
	LocationID     int64        `json:"location_id"`
	Quantity       string       `json:"quantity"`
	CreatedAt      time.Time    `json:"created_at"`
	UpdatedAt      time.Time    `json:"updated_at"`
	DeletedAt      sql.NullTime `json:"deleted_at"`
	ProductName    string       `json:"product_name"`
	ProductSkuCode string       `json:"product_sku_code"`
	ProductUom     string       `json:"product_uom"`
	LocationName   string       `json:"location_name"`
	LocationCode   string       `json:"location_code"`
}

func (q *Queries) ListInventories(ctx context.Context, arg ListInventoriesParams) ([]ListInventoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listInventories, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInventoriesRow
	for rows.Next() {
		var i ListInventoriesRow
		if err := rows.Scan(
			&i.ProductID,
			&i.LocationID,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ProductName,
			&i.ProductSkuCode,
			&i.ProductUom,
			&i.LocationName,
			&i.LocationCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocations = `-- name: ListLocations :many
SELECT id, name, code, created_at, updated_at, deleted_at FROM locations
WHERE deleted_at IS NULL
  AND (name ILIKE $1 OR code ILIKE $1)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListLocationsParams struct {
	Name   string `json:"name"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListLocations(ctx context.Context, arg ListLocationsParams) ([]Location, error) {
	rows, err := q.db.QueryContext(ctx, listLocations, arg.Name, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Location
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, sku_code, uom, created_at, updated_at, deleted_at FROM products
WHERE deleted_at IS NULL
  AND (name ILIKE $1 OR sku_code ILIKE $1)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListProductsParams struct {
	Name   string `json:"name"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProducts, arg.Name, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SkuCode,
			&i.Uom,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLocation = `-- name: UpdateLocation :one
UPDATE locations
SET name = $2, code = $3, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, code, created_at, updated_at, deleted_at
`

type UpdateLocationParams struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	Code string `json:"code"`
}

func (q *Queries) UpdateLocation(ctx context.Context, arg UpdateLocationParams) (Location, error) {
	row := q.db.QueryRowContext(ctx, updateLocation, arg.ID, arg.Name, arg.Code)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET name = $2, sku_code = $3, uom = $4, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, sku_code, uom, created_at, updated_at, deleted_at
`

type UpdateProductParams struct {
	ID      int64  `json:"id"`
	Name    string `json:"name"`
	SkuCode string `json:"sku_code"`
	Uom     string `json:"uom"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, updateProduct,
		arg.ID,
		arg.Name,
		arg.SkuCode,
		arg.Uom,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SkuCode,
		&i.Uom,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
