// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"
)

type Inventory struct {
	ProductID  int64        `json:"product_id"`
	LocationID int64        `json:"location_id"`
	Quantity   string       `json:"quantity"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
	DeletedAt  sql.NullTime `json:"deleted_at"`
}

type Location struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	Code      string       `json:"code"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

type Product struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	SkuCode   string       `json:"sku_code"`
	Uom       string       `json:"uom"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

type Role struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

type User struct {
	ID        int64          `json:"id"`
	Username  string         `json:"username"`
	CreatedAt time.Time      `json:"created_at"`
	Nik       sql.NullString `json:"nik"`
	Password  sql.NullString `json:"password"`
	FullName  sql.NullString `json:"full_name"`
	RoleID    sql.NullInt64  `json:"role_id"`
	UpdatedAt time.Time      `json:"updated_at"`
	DeletedAt sql.NullTime   `json:"deleted_at"`
}
