// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbound_product.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/lib/pq"
)

const bulkCreateDeliveryItems = `-- name: BulkCreateDeliveryItems :exec
INSERT INTO delivery_items (
  delivery_id, product_id, quantity
)
SELECT $1, unnest($2::bigint[]), unnest($3::numeric[])
`

type BulkCreateDeliveryItemsParams struct {
	DeliveryID int64    `json:"delivery_id"`
	Column2    []int64  `json:"column_2"`
	Column3    []string `json:"column_3"`
}

func (q *Queries) BulkCreateDeliveryItems(ctx context.Context, arg BulkCreateDeliveryItemsParams) error {
	_, err := q.db.ExecContext(ctx, bulkCreateDeliveryItems, arg.DeliveryID, pq.Array(arg.Column2), pq.Array(arg.Column3))
	return err
}

const bulkCreateDeliveryOrderItems = `-- name: BulkCreateDeliveryOrderItems :exec
INSERT INTO delivery_order_items (
  delivery_order_id, product_id, quantity
)
SELECT $1, unnest($2::bigint[]), unnest($3::numeric[])
`

type BulkCreateDeliveryOrderItemsParams struct {
	DeliveryOrderID int64    `json:"delivery_order_id"`
	Column2         []int64  `json:"column_2"`
	Column3         []string `json:"column_3"`
}

func (q *Queries) BulkCreateDeliveryOrderItems(ctx context.Context, arg BulkCreateDeliveryOrderItemsParams) error {
	_, err := q.db.ExecContext(ctx, bulkCreateDeliveryOrderItems, arg.DeliveryOrderID, pq.Array(arg.Column2), pq.Array(arg.Column3))
	return err
}

const countCustomers = `-- name: CountCustomers :one
SELECT COUNT(*) FROM customers
WHERE deleted_at IS NULL
`

func (q *Queries) CountCustomers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCustomers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDeliveries = `-- name: CountDeliveries :one
SELECT COUNT(*) FROM deliveries
WHERE deleted_at IS NULL
`

func (q *Queries) CountDeliveries(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDeliveries)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDeliveryOrders = `-- name: CountDeliveryOrders :one
SELECT COUNT(*) FROM delivery_orders
WHERE deleted_at IS NULL
`

func (q *Queries) CountDeliveryOrders(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDeliveryOrders)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (
  name, address, contact_name, contact_info
) VALUES ($1, $2, $3, $4)
RETURNING id, name, address, contact_name, contact_info, created_at, updated_at, deleted_at
`

type CreateCustomerParams struct {
	Name        string         `json:"name"`
	Address     string         `json:"address"`
	ContactName sql.NullString `json:"contact_name"`
	ContactInfo sql.NullString `json:"contact_info"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRowContext(ctx, createCustomer,
		arg.Name,
		arg.Address,
		arg.ContactName,
		arg.ContactInfo,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.ContactName,
		&i.ContactInfo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createDelivery = `-- name: CreateDelivery :one
INSERT INTO deliveries (
  delivery_order_id, user_id, location_id, delivered_at, vehicle_number, note
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, delivery_order_id, user_id, location_id, delivered_at, vehicle_number, note, created_at, updated_at, deleted_at
`

type CreateDeliveryParams struct {
	DeliveryOrderID int64          `json:"delivery_order_id"`
	UserID          int64          `json:"user_id"`
	LocationID      int64          `json:"location_id"`
	DeliveredAt     time.Time      `json:"delivered_at"`
	VehicleNumber   sql.NullString `json:"vehicle_number"`
	Note            sql.NullString `json:"note"`
}

func (q *Queries) CreateDelivery(ctx context.Context, arg CreateDeliveryParams) (Delivery, error) {
	row := q.db.QueryRowContext(ctx, createDelivery,
		arg.DeliveryOrderID,
		arg.UserID,
		arg.LocationID,
		arg.DeliveredAt,
		arg.VehicleNumber,
		arg.Note,
	)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.DeliveryOrderID,
		&i.UserID,
		&i.LocationID,
		&i.DeliveredAt,
		&i.VehicleNumber,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createDeliveryOrder = `-- name: CreateDeliveryOrder :one
INSERT INTO delivery_orders (
  customer_id, order_number, delivery_date, note
) VALUES ($1, $2, $3, $4)
RETURNING id, customer_id, order_number, delivery_date, status, note, created_at, updated_at, deleted_at
`

type CreateDeliveryOrderParams struct {
	CustomerID   int64          `json:"customer_id"`
	OrderNumber  string         `json:"order_number"`
	DeliveryDate time.Time      `json:"delivery_date"`
	Note         sql.NullString `json:"note"`
}

func (q *Queries) CreateDeliveryOrder(ctx context.Context, arg CreateDeliveryOrderParams) (DeliveryOrder, error) {
	row := q.db.QueryRowContext(ctx, createDeliveryOrder,
		arg.CustomerID,
		arg.OrderNumber,
		arg.DeliveryDate,
		arg.Note,
	)
	var i DeliveryOrder
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.OrderNumber,
		&i.DeliveryDate,
		&i.Status,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteCustomer = `-- name: DeleteCustomer :execresult
UPDATE customers
SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteCustomer(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteCustomer, id)
}

const deleteDelivery = `-- name: DeleteDelivery :execresult
UPDATE deliveries
SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteDelivery(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteDelivery, id)
}

const deleteDeliveryOrder = `-- name: DeleteDeliveryOrder :execresult
UPDATE delivery_orders
SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteDeliveryOrder(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteDeliveryOrder, id)
}

const deleteDeliveryOrderItems = `-- name: DeleteDeliveryOrderItems :exec
UPDATE delivery_order_items
SET deleted_at = now()
WHERE delivery_order_id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteDeliveryOrderItems(ctx context.Context, deliveryOrderID int64) error {
	_, err := q.db.ExecContext(ctx, deleteDeliveryOrderItems, deliveryOrderID)
	return err
}

const getCustomer = `-- name: GetCustomer :one
SELECT id, name, address, contact_name, contact_info, created_at, updated_at, deleted_at FROM customers
WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetCustomer(ctx context.Context, id int64) (Customer, error) {
	row := q.db.QueryRowContext(ctx, getCustomer, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.ContactName,
		&i.ContactInfo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDelivery = `-- name: GetDelivery :one
SELECT d.id, d.delivery_order_id, d.user_id, d.location_id, d.delivered_at, d.vehicle_number, d.note, d.created_at, d.updated_at, d.deleted_at, dlo.order_number, u.username as user_name, l.name as location_name
FROM deliveries d
JOIN delivery_orders dlo ON d.delivery_order_id = dlo.id
JOIN users u ON d.user_id = u.id
JOIN locations l ON d.location_id = l.id
WHERE d.id = $1 AND d.deleted_at IS NULL LIMIT 1
`

type GetDeliveryRow struct {
	ID              int64          `json:"id"`
	DeliveryOrderID int64          `json:"delivery_order_id"`
	UserID          int64          `json:"user_id"`
	LocationID      int64          `json:"location_id"`
	DeliveredAt     time.Time      `json:"delivered_at"`
	VehicleNumber   sql.NullString `json:"vehicle_number"`
	Note            sql.NullString `json:"note"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	DeletedAt       sql.NullTime   `json:"deleted_at"`
	OrderNumber     string         `json:"order_number"`
	UserName        string         `json:"user_name"`
	LocationName    string         `json:"location_name"`
}

func (q *Queries) GetDelivery(ctx context.Context, id int64) (GetDeliveryRow, error) {
	row := q.db.QueryRowContext(ctx, getDelivery, id)
	var i GetDeliveryRow
	err := row.Scan(
		&i.ID,
		&i.DeliveryOrderID,
		&i.UserID,
		&i.LocationID,
		&i.DeliveredAt,
		&i.VehicleNumber,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.OrderNumber,
		&i.UserName,
		&i.LocationName,
	)
	return i, err
}

const getDeliveryItems = `-- name: GetDeliveryItems :many
SELECT di.id, di.delivery_id, di.product_id, di.quantity, di.created_at, di.updated_at, di.deleted_at, p.name as product_name, p.sku_code as product_sku_code, p.uom as product_uom
FROM delivery_items di
JOIN products p ON di.product_id = p.id
WHERE di.delivery_id = $1 AND di.deleted_at IS NULL
`

type GetDeliveryItemsRow struct {
	ID             int64        `json:"id"`
	DeliveryID     int64        `json:"delivery_id"`
	ProductID      int64        `json:"product_id"`
	Quantity       string       `json:"quantity"`
	CreatedAt      time.Time    `json:"created_at"`
	UpdatedAt      time.Time    `json:"updated_at"`
	DeletedAt      sql.NullTime `json:"deleted_at"`
	ProductName    string       `json:"product_name"`
	ProductSkuCode string       `json:"product_sku_code"`
	ProductUom     string       `json:"product_uom"`
}

func (q *Queries) GetDeliveryItems(ctx context.Context, deliveryID int64) ([]GetDeliveryItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, getDeliveryItems, deliveryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDeliveryItemsRow
	for rows.Next() {
		var i GetDeliveryItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.DeliveryID,
			&i.ProductID,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ProductName,
			&i.ProductSkuCode,
			&i.ProductUom,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeliveryOrder = `-- name: GetDeliveryOrder :one
SELECT dlo.id, dlo.customer_id, dlo.order_number, dlo.delivery_date, dlo.status, dlo.note, dlo.created_at, dlo.updated_at, dlo.deleted_at, c.name as customer_name, c.address as customer_address
FROM delivery_orders dlo
JOIN customers c ON dlo.customer_id = c.id
WHERE dlo.id = $1 AND dlo.deleted_at IS NULL LIMIT 1
`

type GetDeliveryOrderRow struct {
	ID              int64          `json:"id"`
	CustomerID      int64          `json:"customer_id"`
	OrderNumber     string         `json:"order_number"`
	DeliveryDate    time.Time      `json:"delivery_date"`
	Status          string         `json:"status"`
	Note            sql.NullString `json:"note"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	DeletedAt       sql.NullTime   `json:"deleted_at"`
	CustomerName    string         `json:"customer_name"`
	CustomerAddress string         `json:"customer_address"`
}

func (q *Queries) GetDeliveryOrder(ctx context.Context, id int64) (GetDeliveryOrderRow, error) {
	row := q.db.QueryRowContext(ctx, getDeliveryOrder, id)
	var i GetDeliveryOrderRow
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.OrderNumber,
		&i.DeliveryDate,
		&i.Status,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CustomerName,
		&i.CustomerAddress,
	)
	return i, err
}

const getDeliveryOrderItems = `-- name: GetDeliveryOrderItems :many
SELECT doi.id, doi.delivery_order_id, doi.product_id, doi.quantity, doi.delivered_quantity, doi.created_at, doi.updated_at, doi.deleted_at, p.name as product_name, p.sku_code as product_sku_code, p.uom as product_uom
FROM delivery_order_items doi
JOIN products p ON doi.product_id = p.id
WHERE doi.delivery_order_id = $1 AND doi.deleted_at IS NULL
`

type GetDeliveryOrderItemsRow struct {
	ID                int64        `json:"id"`
	DeliveryOrderID   int64        `json:"delivery_order_id"`
	ProductID         int64        `json:"product_id"`
	Quantity          string       `json:"quantity"`
	DeliveredQuantity string       `json:"delivered_quantity"`
	CreatedAt         time.Time    `json:"created_at"`
	UpdatedAt         time.Time    `json:"updated_at"`
	DeletedAt         sql.NullTime `json:"deleted_at"`
	ProductName       string       `json:"product_name"`
	ProductSkuCode    string       `json:"product_sku_code"`
	ProductUom        string       `json:"product_uom"`
}

func (q *Queries) GetDeliveryOrderItems(ctx context.Context, deliveryOrderID int64) ([]GetDeliveryOrderItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, getDeliveryOrderItems, deliveryOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDeliveryOrderItemsRow
	for rows.Next() {
		var i GetDeliveryOrderItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.DeliveryOrderID,
			&i.ProductID,
			&i.Quantity,
			&i.DeliveredQuantity,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ProductName,
			&i.ProductSkuCode,
			&i.ProductUom,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementDeliveryOrderItemDeliveredQty = `-- name: IncrementDeliveryOrderItemDeliveredQty :exec
UPDATE delivery_order_items
SET delivered_quantity = delivered_quantity + $3,
    updated_at = now()
WHERE delivery_order_id = $1 AND product_id = $2 AND deleted_at IS NULL
`

type IncrementDeliveryOrderItemDeliveredQtyParams struct {
	DeliveryOrderID   int64  `json:"delivery_order_id"`
	ProductID         int64  `json:"product_id"`
	DeliveredQuantity string `json:"delivered_quantity"`
}

func (q *Queries) IncrementDeliveryOrderItemDeliveredQty(ctx context.Context, arg IncrementDeliveryOrderItemDeliveredQtyParams) error {
	_, err := q.db.ExecContext(ctx, incrementDeliveryOrderItemDeliveredQty, arg.DeliveryOrderID, arg.ProductID, arg.DeliveredQuantity)
	return err
}

const listCustomers = `-- name: ListCustomers :many
SELECT id, name, address, contact_name, contact_info, created_at, updated_at, deleted_at FROM customers
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListCustomersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCustomers(ctx context.Context, arg ListCustomersParams) ([]Customer, error) {
	rows, err := q.db.QueryContext(ctx, listCustomers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.ContactName,
			&i.ContactInfo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeliveries = `-- name: ListDeliveries :many
SELECT d.id, d.delivery_order_id, d.user_id, d.location_id, d.delivered_at, d.vehicle_number, d.note, d.created_at, d.updated_at, d.deleted_at, dlo.order_number
FROM deliveries d
JOIN delivery_orders dlo ON d.delivery_order_id = dlo.id
WHERE d.deleted_at IS NULL
ORDER BY d.created_at DESC
LIMIT $1 OFFSET $2
`

type ListDeliveriesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListDeliveriesRow struct {
	ID              int64          `json:"id"`
	DeliveryOrderID int64          `json:"delivery_order_id"`
	UserID          int64          `json:"user_id"`
	LocationID      int64          `json:"location_id"`
	DeliveredAt     time.Time      `json:"delivered_at"`
	VehicleNumber   sql.NullString `json:"vehicle_number"`
	Note            sql.NullString `json:"note"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	DeletedAt       sql.NullTime   `json:"deleted_at"`
	OrderNumber     string         `json:"order_number"`
}

func (q *Queries) ListDeliveries(ctx context.Context, arg ListDeliveriesParams) ([]ListDeliveriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listDeliveries, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDeliveriesRow
	for rows.Next() {
		var i ListDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.DeliveryOrderID,
			&i.UserID,
			&i.LocationID,
			&i.DeliveredAt,
			&i.VehicleNumber,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.OrderNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeliveryOrders = `-- name: ListDeliveryOrders :many
SELECT dlo.id, dlo.customer_id, dlo.order_number, dlo.delivery_date, dlo.status, dlo.note, dlo.created_at, dlo.updated_at, dlo.deleted_at, c.name as customer_name
FROM delivery_orders dlo
JOIN customers c ON dlo.customer_id = c.id
WHERE dlo.deleted_at IS NULL
ORDER BY dlo.created_at DESC
LIMIT $1 OFFSET $2
`

type ListDeliveryOrdersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListDeliveryOrdersRow struct {
	ID           int64          `json:"id"`
	CustomerID   int64          `json:"customer_id"`
	OrderNumber  string         `json:"order_number"`
	DeliveryDate time.Time      `json:"delivery_date"`
	Status       string         `json:"status"`
	Note         sql.NullString `json:"note"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	DeletedAt    sql.NullTime   `json:"deleted_at"`
	CustomerName string         `json:"customer_name"`
}

func (q *Queries) ListDeliveryOrders(ctx context.Context, arg ListDeliveryOrdersParams) ([]ListDeliveryOrdersRow, error) {
	rows, err := q.db.QueryContext(ctx, listDeliveryOrders, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDeliveryOrdersRow
	for rows.Next() {
		var i ListDeliveryOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.OrderNumber,
			&i.DeliveryDate,
			&i.Status,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CustomerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomer = `-- name: UpdateCustomer :one
UPDATE customers
SET name = $2, address = $3, contact_name = $4, contact_info = $5, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, address, contact_name, contact_info, created_at, updated_at, deleted_at
`

type UpdateCustomerParams struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Address     string         `json:"address"`
	ContactName sql.NullString `json:"contact_name"`
	ContactInfo sql.NullString `json:"contact_info"`
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error) {
	row := q.db.QueryRowContext(ctx, updateCustomer,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.ContactName,
		arg.ContactInfo,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.ContactName,
		&i.ContactInfo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateDelivery = `-- name: UpdateDelivery :one
UPDATE deliveries
SET delivery_order_id = $2, user_id = $3, location_id = $4, delivered_at = $5, vehicle_number = $6, note = $7, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, delivery_order_id, user_id, location_id, delivered_at, vehicle_number, note, created_at, updated_at, deleted_at
`

type UpdateDeliveryParams struct {
	ID              int64          `json:"id"`
	DeliveryOrderID int64          `json:"delivery_order_id"`
	UserID          int64          `json:"user_id"`
	LocationID      int64          `json:"location_id"`
	DeliveredAt     time.Time      `json:"delivered_at"`
	VehicleNumber   sql.NullString `json:"vehicle_number"`
	Note            sql.NullString `json:"note"`
}

func (q *Queries) UpdateDelivery(ctx context.Context, arg UpdateDeliveryParams) (Delivery, error) {
	row := q.db.QueryRowContext(ctx, updateDelivery,
		arg.ID,
		arg.DeliveryOrderID,
		arg.UserID,
		arg.LocationID,
		arg.DeliveredAt,
		arg.VehicleNumber,
		arg.Note,
	)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.DeliveryOrderID,
		&i.UserID,
		&i.LocationID,
		&i.DeliveredAt,
		&i.VehicleNumber,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateDeliveryOrder = `-- name: UpdateDeliveryOrder :one
UPDATE delivery_orders
SET customer_id = $2, order_number = $3, delivery_date = $4, status = $5, note = $6, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, customer_id, order_number, delivery_date, status, note, created_at, updated_at, deleted_at
`

type UpdateDeliveryOrderParams struct {
	ID           int64          `json:"id"`
	CustomerID   int64          `json:"customer_id"`
	OrderNumber  string         `json:"order_number"`
	DeliveryDate time.Time      `json:"delivery_date"`
	Status       string         `json:"status"`
	Note         sql.NullString `json:"note"`
}

func (q *Queries) UpdateDeliveryOrder(ctx context.Context, arg UpdateDeliveryOrderParams) (DeliveryOrder, error) {
	row := q.db.QueryRowContext(ctx, updateDeliveryOrder,
		arg.ID,
		arg.CustomerID,
		arg.OrderNumber,
		arg.DeliveryDate,
		arg.Status,
		arg.Note,
	)
	var i DeliveryOrder
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.OrderNumber,
		&i.DeliveryDate,
		&i.Status,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateDeliveryOrderStatus = `-- name: UpdateDeliveryOrderStatus :one
UPDATE delivery_orders
SET status = $2, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, customer_id, order_number, delivery_date, status, note, created_at, updated_at, deleted_at
`

type UpdateDeliveryOrderStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateDeliveryOrderStatus(ctx context.Context, arg UpdateDeliveryOrderStatusParams) (DeliveryOrder, error) {
	row := q.db.QueryRowContext(ctx, updateDeliveryOrderStatus, arg.ID, arg.Status)
	var i DeliveryOrder
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.OrderNumber,
		&i.DeliveryDate,
		&i.Status,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertDeliveryOrderItem = `-- name: UpsertDeliveryOrderItem :one
INSERT INTO delivery_order_items (
  delivery_order_id, product_id, quantity, delivered_quantity
) VALUES ($1, $2, $3, $4)
ON CONFLICT (delivery_order_id, product_id) DO UPDATE SET
  quantity = EXCLUDED.quantity,
  delivered_quantity = EXCLUDED.delivered_quantity,
  updated_at = now(),
  deleted_at = NULL
RETURNING id, delivery_order_id, product_id, quantity, delivered_quantity, created_at, updated_at, deleted_at
`

type UpsertDeliveryOrderItemParams struct {
	DeliveryOrderID   int64  `json:"delivery_order_id"`
	ProductID         int64  `json:"product_id"`
	Quantity          string `json:"quantity"`
	DeliveredQuantity string `json:"delivered_quantity"`
}

func (q *Queries) UpsertDeliveryOrderItem(ctx context.Context, arg UpsertDeliveryOrderItemParams) (DeliveryOrderItem, error) {
	row := q.db.QueryRowContext(ctx, upsertDeliveryOrderItem,
		arg.DeliveryOrderID,
		arg.ProductID,
		arg.Quantity,
		arg.DeliveredQuantity,
	)
	var i DeliveryOrderItem
	err := row.Scan(
		&i.ID,
		&i.DeliveryOrderID,
		&i.ProductID,
		&i.Quantity,
		&i.DeliveredQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
